---
- name: Configure the new Linode instance
  hosts: kali
  gather_facts: false
  tasks:
    - name: pause for 30 seconds
      pause:
        seconds: 120
    - name: Update the system
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        name:
          - git
          - build-essential
          - apt-utils
          - cmake
          - libfontconfig1
          - libglu1-mesa-dev
          - libgtest-dev
          - libspdlog-dev
          - libboost-all-dev
          - libncurses5-dev
          - libgdbm-dev
          - libssl-dev
          - libreadline-dev
          - libffi-dev
          - libsqlite3-dev
          - libbz2-dev
          - mesa-common-dev
          - qtbase5-dev
          - qtchooser
          - qt5-qmake
          - qtbase5-dev-tools
          - libqt5websockets5
          - libqt5websockets5-dev
          - qtdeclarative5-dev
          - golang-go
          - python3-dev
          - mingw-w64
          - nasm
          - nginx
          - ufw
          - snapd
        state: present
