---
- name: Setup Nginx and Firewall
  hosts: kali
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 30
        timeout: 300
        state: started

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Start Snapd service
      service:
        name: snapd
        state: started

    - name: Install Certbot snap
      command: snap install --classic certbot
      become: true

    - name: Symlink Certbot binary
      command: ln -s /snap/bin/certbot /usr/bin/certbot
      become: true
      ignore_errors: yes 

    - name: Modify Nginx default site configuration
      lineinfile:
        path: /etc/nginx/sites-enabled/default
        regexp: '^(\s*)server_name _;'
        line: '        server_name {{ my_domain }};'
      become: true

    - name: Enable UFW firewall
      command: ufw --force enable
      become: true

    - name: Allow SSH through UFW
      command: ufw  allow ssh
      become: true
      ignore_errors: yes 

    - name: Allow HTTP through UFW
      command: ufw  allow http
      become: true

    - name: Allow HTTPS through UFW
      command: ufw  allow https
      become: true

    - name: Allow specific port from my IP address
      command: ufw  allow from {{ my_ip }} to any port 40056
      become: true

    - name: Deny access to port 40056
      command: ufw  deny 40056
      become: true

    - name: Deny access to port 8443
      command: ufw  deny 8443
      become: true

    - name: Add content after "location / {"
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-enabled/default
        insertafter: '^(\s*)location / {$'
        line: |
          if ($http_user_agent ~* "Mozilla/5.0 \(Windows NT 6.1; WOW64\) AppleWebKit/537.36 \(KHTML, like Gecko\) Chrome/96.0.4664.110 Safari/537.36") {
              proxy_pass https://127.0.0.1:8443;
          }
      become: true

    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: true

    - name: Clone bank-html-template repository
      git:
        repo: https://github.com/armirnesimi/bank-html-template
        dest: ~/bank-html-template
      become: true

    - name: Move files to Nginx web root
      ansible.builtin.shell:
        cmd: mv /root/bank-html-template/* /var/www/html/
      become: true
    - name: Nginx full
      ansible.builtin.shell:
        cmd: sudo ufw allow 'Nginx Full'
      become: true
    - name: Obtain SSL certificate with Certbot
      ansible.builtin.shell:
        cmd: certbot --nginx --non-interactive --agree-tos --email {{ my_email }} -d {{ my_domain }}
      become: true
      environment:
        CERTBOT_AUTO: 1
    - name: Run Havoc server
      become: true
      command: nohup ./havoc server --profile profiles/havoc.yaotl &
      args:
        chdir: /opt/Havoc
      async: 0
      poll: 0
 